name: Some Github Actions
on: [push]
jobs:
  Run-Docs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was triggered by ${{ github.event_name }}"
      - run: echo "This job is running on ${{ runner.os }} hosted on Github"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      - name: Check out the repository code
        users: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner"
      - run: echo "The workflow is now ready to test your code on the runner"
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}"
